name: trufi_core_routing
description: A Flutter package for route planning with OTP (OpenTripPlanner) integration.
version: 0.0.1
homepage: https://github.com/trufi-association/trufi-core
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.2.2
  gql: ^1.0.1-alpha+1705015029973
  latlong2: ^0.9.1
  intl: ^0.20.2
  trufi_core_maps:
    path: ../trufi_core_maps

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
