name: trufi_core_maps_example
description: Example app demonstrating trufi_core_maps features.
publish_to: 'none'

environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  trufi_core_maps:
    path: ../
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
