name: trufi_core_maps_example
description: Example app demonstrating trufi_core_maps features.
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  trufi_core_maps:
    path: ../
  latlong2: ^0.9.1
  provider: ^6.1.2
  flutter_map: ^8.2.2
  cached_network_image: ^3.4.1

dependency_overrides:
  trufi_core_interfaces:
    path: ../../trufi_core_interfaces
  trufi_core_utils:
    path: ../../trufi_core_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
