name: trufi_core_map_layers
description: Map layers for trufi_core including bike parks, car sharing, weather stations, and more.
version: 0.0.1
homepage: https://github.com/trufi-association/trufi-core
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_svg: ^2.2.1
  gql: ^1.0.0
  graphql: ^5.2.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  url_launcher: ^6.3.2
  vector_tile: ^3.0.0
  trufi_core_maps:
    path: ../trufi_core_maps
  trufi_core:
    path: ../../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
