name: trufi_core_saved_places_example
description: Example app demonstrating trufi_core_saved_places package.
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.3
  latlong2: ^0.9.1
  provider: ^6.1.2
  trufi_core_maps:
    path: ../../trufi_core_maps
  trufi_core_saved_places:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
