name: trufi_core_notifications
description: "Push and in-app notifications for Trufi Core apps."
version: 1.0.0
homepage:
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  trufi_core_interfaces: ^1.0.0
  trufi_core_utils: ^1.0.0
  http: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
