name: trufi_core_home_screen
description: "Home screen and route planner for trufi_core apps."
version: 0.0.1
homepage:
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  hive: ^2.2.3
  async: ^2.11.0
  trufi_core_interfaces:
    path: ../trufi_core_interfaces
  trufi_core_routing:
    path: ../trufi_core_routing

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
