name: trufi_core_about_example
description: "Example app for trufi_core_about package"
publish_to: none
version: 0.0.1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  trufi_core_about:
    path: ../

dependency_overrides:
  trufi_core_interfaces:
    path: ../../../trufi_core_interfaces
  trufi_core_utils:
    path: ../../../trufi_core_utils
  trufi_core_base_widgets:
    path: ../../../trufi_core_base_widgets
  trufi_core_custom_material:
    path: ../../../trufi_core_custom_material

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
