name: trufi_core_ui
description: "Core UI components and app shell for Trufi Core apps."
version: 1.0.0
homepage:
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.5+1
  go_router: ^17.0.1
  app_links: ^7.0.0
  trufi_core_interfaces: ^1.0.0
  trufi_core_utils: ^1.0.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
