name: trufi_core_maps
description: A Flutter package for map rendering with support for flutter_map and maplibre_gl.
version: 1.0.0
homepage: https://github.com/trufi-association/trufi-core
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  flutter_map: ^7.0.2
  flutter_svg: ^2.2.3
  hive: ^2.2.3
  latlong2: ^0.9.1
  maplibre_gl: ^0.24.1
  url_launcher: ^6.3.0
  vector_tile: ^3.0.0
  trufi_core_interfaces: ^1.0.0
  trufi_core_storage: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
