name: trufi_core_maps
description: A Flutter package for map rendering with support for flutter_map, maplibre_gl, and maplibre.
version: 1.0.0
homepage: https://github.com/trufi-association/trufi-core
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  equatable: ^2.0.8
  flutter_bloc: ^9.1.1
  flutter_map: ^8.2.2
  flutter_svg: ^2.2.3
  latlong2: ^0.9.1
  maplibre: ^0.3.3+2
  maplibre_gl: ^0.25.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  vector_tile: ^3.0.0
  trufi_core_interfaces: ^1.0.0
  trufi_core_utils: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
