name: trufi_core_maps
description: A Flutter package for map rendering with support for flutter_map and maplibre_gl.
version: 0.0.1
homepage: https://github.com/trufi-association/trufi-core
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0
  flutter_map: ^7.0.2
  flutter_svg: ^2.2.3
  latlong2: ^0.9.1
  maplibre_gl: ^0.24.1
  vector_tile: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
