name: trufi_core_poi_layers_example
description: Example app demonstrating trufi_core_poi_layers features.
publish_to: none

environment:
  sdk: ^3.10.0
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  trufi_core_poi_layers:
    path: ../
  trufi_core_maps:
    path: ../../trufi_core_maps
  trufi_core_base_widgets:
    path: ../../trufi_core_base_widgets
  latlong2: ^0.9.1
  flutter_bloc: ^8.1.6
  provider: ^6.1.2

dependency_overrides:
  trufi_core_interfaces:
    path: ../../trufi_core_interfaces
  trufi_core_utils:
    path: ../../trufi_core_utils
  trufi_core_custom_material:
    path: ../../trufi_core_custom_material

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/pois/
