name: trufi_core_transport_list_example
description: Example app demonstrating trufi_core_transport_list package.
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  latlong2: ^0.9.1
  provider: ^6.1.5+1
  trufi_core_transport_list:
    path: ../
  trufi_core_maps:
    path: ../../../trufi_core_maps
  trufi_core_routing:
    path: ../../../trufi_core_routing

dependency_overrides:
  trufi_core_base_widgets:
    path: ../../../trufi_core_base_widgets
  trufi_core_custom_material:
    path: ../../../trufi_core_custom_material
  trufi_core_interfaces:
    path: ../../../trufi_core_interfaces
  trufi_core_maps:
    path: ../../../trufi_core_maps
  trufi_core_routing:
    path: ../../../trufi_core_routing
  trufi_core_utils:
    path: ../../../trufi_core_utils

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
